name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pytest
        pip install -r src/requirements.txt

    - name: Install Firefox
      run: |
        sudo apt-get update
        sudo apt-get install -y firefox

    - name: Install Geckodriver
      run: |
        wget https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz
        tar -xzf geckodriver-v0.30.0-linux64.tar.gz
        sudo mv geckodriver /usr/local/bin/

    - name: Debug file structure (current directory)
      run: |
        ls -R

    - name: Run tests
      run: |
        python -m pytest src/tests
