name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Debug file structure
      run: |
        ls -R
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        cd Flask-Login-System
        pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
    - name: Run tests
      run: |
        cd Flask-Login-System
        python -m pytest src/tests
